### ISSUE TITLE
erreur bloquante workflow githubPages

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-workflows#13]
**Description du BUG**

https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/actions/runs/7902601296

**Copies d'ecran**

![image](https://github.com/ansforge/IG-workflows/assets/117643165/a796a9f1-a2ab-4a41-a67b-1612334777fa)

**Autres informations**

**Comment by M-Priour** [comment]
le problème est maintenant résolu avec la PR
