### ISSUE TITLE
Suppression du script call-sushi

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-workflows#6]
https://github.com/ansforge/IG-workflows/blob/79a16956f3d512cded2a4692c81a8529afb029da/.github/workflows/fhir-worklows.yml#L10C7-L10C8

Peut-on supprimer le script call-sushi ? Sushi est également appelé dans call-Test-Unitaire dans fhir-validator-engine

https://github.com/ansforge/IG-workflows/blob/79a16956f3d512cded2a4692c81a8529afb029da/.github/workflows/fhir-validator-engine.yml

**Comment by M-Priour** [comment]
Ce problème n existe plus avec le nouveau workflow qui fait tout dans la même action
